ProyectoP1Bancos/Controllers/CuentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoP1Bancos.Data;
using ProyectoP1Bancos.Models;

namespace ProyectoP1Bancos.Controllers
{
    public class CuentasController : Controller
    {
        private readonly ProyectoP1BancosContext _context;

        public CuentasController(ProyectoP1BancosContext context)
        {
            _context = context;
        }

        // GET: Cuentas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cuenta.ToListAsync());
        }

        // GET: Cuentas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuenta
                .FirstOrDefaultAsync(m => m.IdCuenta == id);
            if (cuenta == null)
            {
                return NotFound();
            }

            return View(cuenta);
        }

        // GET: Cuentas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cuentas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCuenta,NumCuenta")] Cuenta cuenta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cuenta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cuenta);
        }

        // GET: Cuentas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuenta.FindAsync(id);
            if (cuenta == null)
            {
                return NotFound();
            }
            return View(cuenta);
        }

        // POST: Cuentas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCuenta,NumCuenta")] Cuenta cuenta)
        {
            if (id != cuenta.IdCuenta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cuenta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CuentaExists(cuenta.IdCuenta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cuenta);
        }

        // GET: Cuentas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cuenta = await _context.Cuenta
                .FirstOrDefaultAsync(m => m.IdCuenta == id);
            if (cuenta == null)
            {
                return NotFound();
            }

            return View(cuenta);
        }

        // POST: Cuentas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cuenta = await _context.Cuenta.FindAsync(id);
            if (cuenta != null)
            {
                _context.Cuenta.Remove(cuenta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CuentaExists(int id)
        {
            return _context.Cuenta.Any(e => e.IdCuenta == id);
        }
    }
}

ProyectoP1Bancos/Controllers/ObjetoDesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoP1Bancos.Data;
using ProyectoP1Bancos.Models;

namespace ProyectoP1Bancos.Controllers
{
    public class ObjetoDesController : Controller
    {
        private readonly ProyectoP1BancosContext _context;

        public ObjetoDesController(ProyectoP1BancosContext context)
        {
            _context = context;
        }

        // GET: ObjetoDes
        public async Task<IActionResult> Index()
        {
            return View(await _context.ObjetoDes.ToListAsync());
        }

        // GET: ObjetoDes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objetoDes = await _context.ObjetoDes
                .FirstOrDefaultAsync(m => m.IdObjeto == id);
            if (objetoDes == null)
            {
                return NotFound();
            }

            return View(objetoDes);
        }

        // GET: ObjetoDes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ObjetoDes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdObjeto,NombreObjeto,Precio,Descripcion")] ObjetoDes objetoDes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(objetoDes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(objetoDes);
        }

        // GET: ObjetoDes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objetoDes = await _context.ObjetoDes.FindAsync(id);
            if (objetoDes == null)
            {
                return NotFound();
            }
            return View(objetoDes);
        }

        // POST: ObjetoDes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdObjeto,NombreObjeto,Precio,Descripcion")] ObjetoDes objetoDes)
        {
            if (id != objetoDes.IdObjeto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(objetoDes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ObjetoDesExists(objetoDes.IdObjeto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(objetoDes);
        }

        // GET: ObjetoDes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var objetoDes = await _context.ObjetoDes
                .FirstOrDefaultAsync(m => m.IdObjeto == id);
            if (objetoDes == null)
            {
                return NotFound();
            }

            return View(objetoDes);
        }

        // POST: ObjetoDes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var objetoDes = await _context.ObjetoDes.FindAsync(id);
            if (objetoDes != null)
            {
                _context.ObjetoDes.Remove(objetoDes);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ObjetoDesExists(int id)
        {
            return _context.ObjetoDes.Any(e => e.IdObjeto == id);
        }
    }
}

ProyectoP1Bancos/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoP1Bancos.Data;
using ProyectoP1Bancos.Models;

namespace ProyectoP1Bancos.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly ProyectoP1BancosContext _context;

        public UsuariosController(ProyectoP1BancosContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            var proyectoP1BancosContext = _context.Usuario.Include(u => u.Cuenta).OrderBy(u => u.Nombre);
            return View(await proyectoP1BancosContext.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
           
            var usuario = await _context.Usuario
                .Include(u => u.Cuenta)
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            ViewData["CuentaIdCuenta"] = new SelectList(_context.Cuenta, "IdCuenta", "NumCuenta");
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Usuario usuario)
        {
            //System.Console.Write(ModelState.IsValid);
            // if (ModelState.IsValid)
            //{
            Usuario usuario2 = await _context.Usuario.FirstOrDefaultAsync(x => x.Cedula == usuario.Cedula);
            Usuario usuario3 = await _context.Usuario.FirstOrDefaultAsync(x => x.CuentaIdCuenta == usuario.CuentaIdCuenta);
            if (usuario2 == null && usuario3 == null)
            {
                
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            else
            {
                ModelState.AddModelError(string.Empty, "Ya existe un usuario con esta cédula o cuenta, Porvafor regrese");
                return View();
            }

            //Usuario usuario3 = await _context.Usuario.FirstOrDefault(x => x.Cedula == usuario.);


            //}

            // ViewData["CuentaIdCuenta"] = new SelectList(_context.Cuenta, "IdCuenta", "NumCuenta", usuario.CuentaIdCuenta);
            //return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            ViewData["CuentaIdCuenta"] = new SelectList(_context.Cuenta, "IdCuenta", "NumCuenta", usuario.CuentaIdCuenta);
            return View(usuario);

        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuario,Nombre,Apellido,Cedula,Telefono,CuentaIdCuenta")] Usuario usuario)
        {
            if (id != usuario.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CuentaIdCuenta"] = new SelectList(_context.Cuenta, "IdCuenta", "NumCuenta", usuario.CuentaIdCuenta);
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .Include(u => u.Cuenta)
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuario.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuario.Any(e => e.IdUsuario == id);
        }
    }
}

ProyectoP1Bancos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoP1Bancos</title>

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/aos/aos.css" rel="stylesheet">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="d-flex align-items-center ">
        <div class="container-fluid container-xxl d-flex align-items-center">

            <div id="logo" class="me-auto">
                <!-- Uncomment below if you prefer to use a text logo -->
                <!-- <h1><a href="index.html">The<span>Event</span></a></h1>-->
                <a href="#hero" class="scrollto"><img src="~/img/pene.png" alt="" title=""></a>
            </div>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                   <li><a class="nav-link scrollto active" href="#hero">Casita</a></li>
                    @* <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#speakers">Speakers</a></li>
                    <li><a class="nav-link scrollto" href="#schedule">Schedule</a></li>
                    <li><a class="nav-link scrollto" href="#venue">Venue</a></li>
                    <li><a class="nav-link scrollto" href="#hotels">Hotels</a></li>
                    <li><a class="nav-link scrollto" href="#gallery">Gallery</a></li>
                    <li><a class="nav-link scrollto" href="#supporters">Sponsors</a></li>  *@
                    <!-- <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                      <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                          <ul>
                            <li><a href="#">Deep Drop Down 1</a></li>
                            <li><a href="#">Deep Drop Down 2</a></li>
                            <li><a href="#">Deep Drop Down 3</a></li>
                            <li><a href="#">Deep Drop Down 4</a></li>
                            <li><a href="#">Deep Drop Down 5</a></li>
                          </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                      </ul>
                    </li> -->
                    @* <li><a class="nav-link scrollto" href="#contact">Contact</a></li> *@
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
            <a class="buy-tickets scrollto" href="@Url.Action("Inicio","RegistroUsuarios")">Iniciar Sesión</a>
            <a class="buy-tickets scrollto" href="@Url.Action("Register","RegistroUsuarios")">Registrate</a>
            
            <a class="buy-tickets scrollto" href="@Url.Action("Ayuda", "RegistroUsuarios")">Ayuda</a>

        </div>
    </header><!-- End Header -->

    <main id="main">
        @RenderBody()
    </main>


    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong>José Sánchez</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=TheEvent
                -->
                Designed by <a href="https://bootstrapmade.com/">GorkyAnge</a>
            </div>
        </div>
    </footer><!-- End  Footer -->

    <!-- Vendor JS Files -->
    <script src="~/lib/aos/aos.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/swiper/swiper-bundle.min.js"></script>
    <script src="~/lib/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoP1Bancos/Views/Shared/_LayoutGay.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoP1Bancos</title>

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/aos/aos.css" rel="stylesheet">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="d-flex align-items-center ">
        <div class="container-fluid container-xxl d-flex align-items-center">

            <div id="logo" class="me-auto">
                <!-- Uncomment below if you prefer to use a text logo -->
                <!-- <h1><a href="index.html">The<span>Event</span></a></h1>-->
                <a href="#hero" class="scrollto"><img src="~/img/pene.png" alt="" title=""></a>
            </div>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                   <li><a class="nav-link scrollto active" href="#hero">Casita</a></li>
                    @* <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#speakers">Speakers</a></li>
                    <li><a class="nav-link scrollto" href="#schedule">Schedule</a></li>
                    <li><a class="nav-link scrollto" href="#venue">Venue</a></li>
                    <li><a class="nav-link scrollto" href="#hotels">Hotels</a></li>
                    <li><a class="nav-link scrollto" href="#gallery">Gallery</a></li>
                    <li><a class="nav-link scrollto" href="#supporters">Sponsors</a></li>  *@
                    <!-- <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                      <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                          <ul>
                            <li><a href="#">Deep Drop Down 1</a></li>
                            <li><a href="#">Deep Drop Down 2</a></li>
                            <li><a href="#">Deep Drop Down 3</a></li>
                            <li><a href="#">Deep Drop Down 4</a></li>
                            <li><a href="#">Deep Drop Down 5</a></li>
                          </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                      </ul>
                    </li> -->
                    @* <li><a class="nav-link scrollto" href="#contact">Contact</a></li> *@
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
           
            <a class ="buy-tickets scrollto" href="@Url.Action("Index", "Usuarios")">Usuario</a>
            <a class="buy-tickets scrollto" href="@Url.Action("Index", "Cuentas")">Cuenta</a>
            <a class="buy-tickets scrollto" href="@Url.Action("Index", "ObjetoDes")">Objetivo</a>
            <a class="buy-tickets scrollto" href="@Url.Action("Ayuda", "RegistroUsuarios")">Ayuda</a>

        </div>
    </header><!-- End Header -->

    <main id="main">
        @RenderBody()
    </main>


    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong>José Sánchez</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=TheEvent
                -->
                Designed by <a href="https://bootstrapmade.com/">GorkyAnge</a>
            </div>
        </div>
    </footer><!-- End  Footer -->

    <!-- Vendor JS Files -->
    <script src="~/lib/aos/aos.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/swiper/swiper-bundle.min.js"></script>
    <script src="~/lib/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoP1Bancos/Views/Shared/_LayoutHetero.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoP1Bancos</title>

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/aos/aos.css" rel="stylesheet">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap-icons/vapor.css" rel="stylesheet">
    <link href="~/lib/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="d-flex align-items-center ">
        <div class="container-fluid container-xxl d-flex align-items-center">

            <div id="logo" class="me-auto">
                <!-- Uncomment below if you prefer to use a text logo -->
                <!-- <h1><a href="index.html">The<span>Event</span></a></h1>-->
                
            </div>

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    @*<li><a class="nav-link scrollto active" href="#hero">Home</a></li>*@
                    @* <li><a class="nav-link scrollto" href="#about">About</a></li>
                    <li><a class="nav-link scrollto" href="#speakers">Speakers</a></li>
                    <li><a class="nav-link scrollto" href="#schedule">Schedule</a></li>
                    <li><a class="nav-link scrollto" href="#venue">Venue</a></li>
                    <li><a class="nav-link scrollto" href="#hotels">Hotels</a></li>
                    <li><a class="nav-link scrollto" href="#gallery">Gallery</a></li>
                    <li><a class="nav-link scrollto" href="#supporters">Sponsors</a></li>  *@
                    <!-- <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                      <ul>
                        <li><a href="#">Drop Down 1</a></li>
                        <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                          <ul>
                            <li><a href="#">Deep Drop Down 1</a></li>
                            <li><a href="#">Deep Drop Down 2</a></li>
                            <li><a href="#">Deep Drop Down 3</a></li>
                            <li><a href="#">Deep Drop Down 4</a></li>
                            <li><a href="#">Deep Drop Down 5</a></li>
                          </ul>
                        </li>
                        <li><a href="#">Drop Down 2</a></li>
                        <li><a href="#">Drop Down 3</a></li>
                        <li><a href="#">Drop Down 4</a></li>
                      </ul>
                    </li> -->
                    @* <li><a class="nav-link scrollto" href="#contact">Contact</a></li> *@
               
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
           
            <a class="buy-tickets scrollto" href="@Url.Action("IndexGay", "Home")">Volver</a>

        </div>
    </header><!-- End Header -->

    <main id="main">
        @RenderBody()
    </main>


    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong>José Sánchez</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=TheEvent
                -->
                Designed by <a href="https://bootstrapmade.com/">GorkyAnge</a>
            </div>
        </div>
    </footer><!-- End  Footer -->

    <!-- Vendor JS Files -->
    <script src="~/lib/aos/aos.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/swiper/swiper-bundle.min.js"></script>
    <script src="~/lib/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>