ProyectoP1Bancos/Models/RegistroUsuario.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoP1Bancos.Models
{
    public class RegistroUsuario
    {
        [Key]
        public int IdRegistro { get; set; }
        [Required (ErrorMessage = "Este campo es obligatorio")]
        public string NombreUsuario { get; set; }
        [Required (ErrorMessage = "Este campo es obligatorio")]
        public string Contraseña { get; set;}
        
       

    }
}

ProyectoP1Bancos/Controllers/RegistroUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoP1Bancos.Data;
using ProyectoP1Bancos.Models;

namespace ProyectoP1Bancos.Controllers
{
    public class RegistroUsuariosController : Controller
    {
        private readonly ProyectoP1BancosContext _context;
       

        public RegistroUsuariosController(ProyectoP1BancosContext context)
        {
            
            _context = context;
        }

        // GET: RegistroUsuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.RegistroUsuario.ToListAsync());
        }

        // GET: RegistroUsuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registroUsuario = await _context.RegistroUsuario
                .FirstOrDefaultAsync(m => m.IdRegistro == id);
            if (registroUsuario == null)
            {
                return NotFound();
            }

            return View(registroUsuario);
        }

        // GET: RegistroUsuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Inicio()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        public IActionResult IndexGay(string nombre, string contraseña)
        {
            var usuario = _context.RegistroUsuario.FirstOrDefault(u => u.NombreUsuario == nombre && u.Contraseña == contraseña);

            if (usuario != null)
            {

                return RedirectToAction("IndexGay", "Home");
            }
            else
            {
                ViewBag.ErrorMessage = "Nombre o contraseña incorrectos.";
                return View();
            }

        }


        // POST: RegistroUsuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRegistro,NombreUsuario,Contraseña")] RegistroUsuario registroUsuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(registroUsuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(registroUsuario);
        }

        // GET: RegistroUsuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registroUsuario = await _context.RegistroUsuario.FindAsync(id);
            if (registroUsuario == null)
            {
                return NotFound();
            }
            return View(registroUsuario);
        }

        // POST: RegistroUsuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRegistro,NombreUsuario,Contraseña")] RegistroUsuario registroUsuario)
        {
            if (id != registroUsuario.IdRegistro)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registroUsuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistroUsuarioExists(registroUsuario.IdRegistro))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registroUsuario);
        }

        // GET: RegistroUsuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registroUsuario = await _context.RegistroUsuario
                .FirstOrDefaultAsync(m => m.IdRegistro == id);
            if (registroUsuario == null)
            {
                return NotFound();
            }

            return View(registroUsuario);
        }

        // POST: RegistroUsuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registroUsuario = await _context.RegistroUsuario.FindAsync(id);
            if (registroUsuario != null)
            {
                _context.RegistroUsuario.Remove(registroUsuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegistroUsuarioExists(int id)
        {
            return _context.RegistroUsuario.Any(e => e.IdRegistro == id);
        }
    }
}

ProyectoP1Bancos/Views/RegistroUsuarios/Ayuda.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_LayoutHetero.cshtml";

}
<H1>Para que sirve METACHAMPO?</H1>
<div>
    <h4>Esta pagina web esta hecha para que puedas crear una meta financiera fija, puede ser sobre un plan de ahorros o tambien sobre un algun objeto que quieras
        pongamos de ejemplo un auto, cuanto costaria el auto? Es informacion la puedes ingresar y tambien proponer una meta para saber cuanto dinero debes gastar
        y comenzar a ahorrar.

        Los integrantes de este equipo fueron:
        Jose Sanchez, Junior Espin y Xavier Gordillo

    </h4>

   
</div>
<div>
    
</div>

ProyectoP1Bancos/Views/RegistroUsuarios/Create.cshtml
@model ProyectoP1Bancos.Models.RegistroUsuario

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>RegistroUsuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraseña" class="control-label"></label>
                <input asp-for="Contraseña" class="form-control" />
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoP1Bancos/Views/RegistroUsuarios/Delete.cshtml
@model ProyectoP1Bancos.Models.RegistroUsuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RegistroUsuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contraseña)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdRegistro" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProyectoP1Bancos/Views/RegistroUsuarios/Details.cshtml
@model ProyectoP1Bancos.Models.RegistroUsuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>RegistroUsuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contraseña)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdRegistro">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProyectoP1Bancos/Views/RegistroUsuarios/Edit.cshtml
@model ProyectoP1Bancos.Models.RegistroUsuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>RegistroUsuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdRegistro" />
            <div class="form-group">
                <label asp-for="NombreUsuario" class="control-label"></label>
                <input asp-for="NombreUsuario" class="form-control" />
                <span asp-validation-for="NombreUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraseña" class="control-label"></label>
                <input asp-for="Contraseña" class="form-control" />
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoP1Bancos/Views/RegistroUsuarios/Index.cshtml
@model IEnumerable<ProyectoP1Bancos.Models.RegistroUsuario>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contraseña)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contraseña)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdRegistro">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdRegistro">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdRegistro">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ProyectoP1Bancos/Views/RegistroUsuarios/Inicio.cshtml
@{
    Layout = null;
}

<head>
    <link rel="stylesheet" href="~/css/register.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoP1Bancos.styles.css" asp-append-version="true" />
    <script src="~/js/register.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>



<div class='box'>
    <div class='box-form'>
        <div class='box-login-tab'></div>
        <div class='box-login-title'>
            <div class='i i-login'></div><h2>LOGIN</h2>
        </div>
        <div class='box-login'>
            <div class='fieldset-body' id='login_form'>
                <button onclick="openLoginInfo();" class='b b-form i i-more' title='Mais Informações'></button>
                <p class='field'>
                    <label for='user'>Nombre Usuario</label>
                    <input as-for="NombreUsuario" type='text' id='user' name='user' title='Username' />
                    <span id='valida' class='i i-warning'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Contraseña</label>
                    <input type='password' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>
                <p class='field'>
                    <label>Aun no te has registrado?</label>

                    . <button onclick="window.location.href='@Url.Action("Register","RegistroUsuarios")'" class="b-cta" title="Registrate">REGISTRATE</button>


                </p>


                <input type='submit' id='do_login' onclick="window.location.href= '@Url.Action("IndexGay","Home")'" value='Iniciar Sesion' title='Get Started' />


            </div>
        </div>
    </div>
    <div class='box-info'>
        <p>
            <button onclick="closeLoginInfo();" class='b b-info i i-left' title='Back to Sign In'></button><h3>Need Help?</h3>
        </p>
        <div class='line-wh'></div>
        <button onclick="" class='b-support' title='Forgot Password?'> Forgot Password?</button>
        <button onclick="" class='b-support' title='Contact Support'> Contact Support</button>
        <div class='line-wh'></div>
        <button onclick="" class='b-cta' title='Sign up now!'> CREATE ACCOUNT</button>
    </div>
</div>


<div class='icon-credits'>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>, <a href="http://www.flaticon.com/authors/budi-tanrim" title="Budi Tanrim">Budi Tanrim</a> & <a href="http://www.flaticon.com/authors/nice-and-serious" title="Nice and Serious">Nice and Serious</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

<div class='icon-credits'>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>, <a href="http://www.flaticon.com/authors/budi-tanrim" title="Budi Tanrim">Budi Tanrim</a> & <a href="http://www.flaticon.com/authors/nice-and-serious" title="Nice and Serious">Nice and Serious</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

ProyectoP1Bancos/Views/RegistroUsuarios/Register.cshtml
@{
    Layout = null;
}

<head>
    <link rel="stylesheet" href="~/css/register.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoP1Bancos.styles.css" asp-append-version="true" />
    <script src="~/js/register.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>



<div class='box'>
    <div class='box-form'>
        <div class='box-login-tab'></div>
        <div class='box-login-title'>
            <div class='i i-login'></div><h2>REGISTRO</h2>
        </div>
        <div class='box-login'>
            <div class='fieldset-body' id='login_form'>
                <button onclick="openLoginInfo();" class='b b-form i i-more' title='Mais Informações'></button>
                <p class='field'>
                    <label for='user'>Nombre Usuario</label>
                    <input type='text' id='user' name='user' title='Username' />
                    <span id='valida' class='i i-warning'></span>
                </p>
                <p class='field'>
                    <label for='pass'>Contraseña</label>
                    <input type='password' id='pass' name='pass' title='Password' />
                    <span id='valida' class='i i-close'></span>
                </p>


                <input type='submit' id='do_login' onclick="window.location.href= '@Url.Action("IndexGay","Home")'" value='REGISTRATE' title='Get Started' />
            </div>
        </div>
    </div>
    <div class='box-info'>
        <p>
            <button onclick="closeLoginInfo();" class='b b-info i i-left' title='Back to Sign In'></button><h3>Puto el que lo lea</h3>
        </p>

    </div>
</div>


<div class='icon-credits'>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a>, <a href="http://www.flaticon.com/authors/budi-tanrim" title="Budi Tanrim">Budi Tanrim</a> & <a href="http://www.flaticon.com/authors/nice-and-serious" title="Nice and Serious">Nice and Serious</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>